# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kalkulyator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    bir = ""
    ikki = ""
    uch = ""
    tort = ""
    besh = ""
    olti = ""
    yetti = ""
    sakkiz = ""
    toqqiz = ""
    nol = ""
    birinchiSon = ""
    amal = ""
    ozgartirish1 = 0
    ozgartirish2 = 0
    #---------------------------------------------

    def Bir(self):
        if(self.oyna.text() == "0"):
            self.oyna.clear()
            self.bir = self.oyna.text()
            self.bir += "1"
            self.oyna.setText(self.bir)
        else:
            self.bir = self.oyna.text()
            self.bir += "1"
            self.oyna.setText(self.bir)
    
    def Ikki(self):
        if(self.oyna.text() == "0"):
            self.oyna.clear()
            self.ikki = self.oyna.text()
            self.ikki += "2"
            self.oyna.setText(self.ikki)
        else:
            self.ikki = self.oyna.text()
            self.ikki += "2"
            self.oyna.setText(self.ikki)

    def Uch(self):
        if(self.oyna.text() == "0"):
            self.oyna.clear()
            self.uch = self.oyna.text()
            self.uch += "3"
            self.oyna.setText(self.uch)
        else:
            self.uch = self.oyna.text()
            self.uch += "3"
            self.oyna.setText(self.uch)
    
    def Tort(self):
        if(self.oyna.text() == "0"):
            self.oyna.clear()
            self.tort = self.oyna.text()
            self.tort += "4"
            self.oyna.setText(self.tort)
        else:
            self.tort = self.oyna.text()
            self.tort += "4"
            self.oyna.setText(self.tort)

    def Besh(self):
        if(self.oyna.text() == "0"):
            self.oyna.clear()
            self.besh = self.oyna.text()
            self.besh += "5"
            self.oyna.setText(self.besh)
        else:
            self.besh = self.oyna.text()
            self.besh += "5"
            self.oyna.setText(self.besh)

    def Olti(self):
        if(self.oyna.text() == "0"):
            self.oyna.clear()
            self.olti = self.oyna.text()
            self.olti += "6"
            self.oyna.setText(self.olti)
        else:
            self.olti = self.oyna.text()
            self.olti += "6"
            self.oyna.setText(self.olti)
    
    def Yetti(self):
        if(self.oyna.text() == "0"):
            self.oyna.clear()
            self.yetti = self.oyna.text()
            self.yetti += "7"
            self.oyna.setText(self.yetti)
        else:
            self.yetti = self.oyna.text()
            self.yetti += "7"
            self.oyna.setText(self.yetti)

    def Sakkiz(self):
        if(self.oyna.text() == "0"):
            self.oyna.clear()
            self.sakkiz = self.oyna.text()
            self.sakkiz += "8"
            self.oyna.setText(self.sakkiz)
        else:
            self.sakkiz = self.oyna.text()
            self.sakkiz += "8"
            self.oyna.setText(self.sakkiz)
    
    def Toqqiz(self):
        if(self.oyna.text() == "0"):
            self.oyna.clear()
            self.toqqiz = self.oyna.text()
            self.toqqiz += "9"
            self.oyna.setText(self.toqqiz)
        else:
            self.toqqiz = self.oyna.text()
            self.toqqiz += "9"
            self.oyna.setText(self.toqqiz)
    
    def Nol(self):
        if(self.oyna.text() == "0"):
            self.oyna.clear()
            self.nol = self.oyna.text()
            self.nol += "0"
            self.oyna.setText(self.nol)
        else:
            self.nol = self.oyna.text()
            self.nol += "0"
            self.oyna.setText(self.nol)

    def Bolish(self):
        self.birinchiSon = self.oyna.text()
        self.amal = "/"
        self.oyna.clear()
        self.oyna.setText("0")

    def Kopaytirish(self):
        self.birinchiSon = self.oyna.text()
        self.amal = "*"
        self.oyna.clear()
        self.oyna.setText("0")
    
    def Olish(self):
        self.birinchiSon = self.oyna.text()
        self.amal = "-"
        self.oyna.clear()
        self.oyna.setText("0")
    
    def Qoshish(self):
        self.birinchiSon = self.oyna.text()
        self.amal = "+"
        self.oyna.clear()
        self.oyna.setText("0")
        
    def Teng(self):
        self.ozgartirish1 = float(self.birinchiSon)
        self.ozgartirish2 = float(self.oyna.text())
        if(self.amal == "/"):
            self.oyna.setText((str(self.ozgartirish1 / self.ozgartirish2)))
        elif(self.amal == "*"):
            self.oyna.setText((str(self.ozgartirish1 * self.ozgartirish2)))
        elif(self.amal == "-"):
            self.oyna.setText((str(self.ozgartirish1 - self.ozgartirish2)))
        elif(self.amal == "+"):
            self.oyna.setText((str(self.ozgartirish1 + self.ozgartirish2)))
        


    def Tozalash(self):
        self.oyna.clear()
        self.oyna.setText("0")

#-----------------------------------------------


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(378, 527)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.oyna = QtWidgets.QLineEdit(self.centralwidget)
        self.oyna.setGeometry(QtCore.QRect(20, 30, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.oyna.setFont(font)
        self.oyna.setInputMask("")
        self.oyna.setMaxLength(32747)
        self.oyna.setFrame(False)
        self.oyna.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.oyna.setCursorPosition(1)
        self.oyna.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.oyna.setObjectName("oyna")

        #7
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 120, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(self.Yetti)

        #8
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(110, 120, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.clicked.connect(self.Sakkiz)

        #9
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(200, 120, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_17.clicked.connect(self.Toqqiz)

        self.bolish = QtWidgets.QPushButton(self.centralwidget)
        self.bolish.setGeometry(QtCore.QRect(290, 120, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bolish.setFont(font)
        self.bolish.setObjectName("bolish")
        self.bolish.clicked.connect(self.Bolish)

        #4
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 210, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.Tort)

        #5
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(110, 210, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.Besh)

        #6
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(200, 210, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.Olti)

        self.kopaytrish = QtWidgets.QPushButton(self.centralwidget)
        self.kopaytrish.setGeometry(QtCore.QRect(290, 210, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.kopaytrish.setFont(font)
        self.kopaytrish.setObjectName("kopaytrish")
        self.kopaytrish.clicked.connect(self.Kopaytirish)

        #1
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(20, 300, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_1.clicked.connect(self.Bir)

        #2
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(110, 300, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.Ikki)

        #3
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(200, 300, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(self.Uch)

        self.olish = QtWidgets.QPushButton(self.centralwidget)
        self.olish.setGeometry(QtCore.QRect(290, 310, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.olish.setFont(font)
        self.olish.setObjectName("olish")
        self.olish.clicked.connect(self.Olish)

        self.qoshish = QtWidgets.QPushButton(self.centralwidget)
        self.qoshish.setGeometry(QtCore.QRect(290, 390, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.qoshish.setFont(font)
        self.qoshish.setObjectName("qoshish")
        self.qoshish.clicked.connect(self.Qoshish)

        self.teng = QtWidgets.QPushButton(self.centralwidget)
        self.teng.setGeometry(QtCore.QRect(200, 390, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.teng.setFont(font)
        self.teng.setObjectName("teng")
        self.teng.clicked.connect(self.Teng)

        #0
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(110, 390, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_0.clicked.connect(self.Nol)

        self.tozalash = QtWidgets.QPushButton(self.centralwidget)
        self.tozalash.setGeometry(QtCore.QRect(20, 390, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tozalash.setFont(font)
        self.tozalash.setObjectName("tozalash")
        self.tozalash.clicked.connect(self.Tozalash)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 378, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.oyna.setText(_translate("MainWindow", "0"))
        self.pushButton_11.setText(_translate("MainWindow", "7"))
        self.pushButton_15.setText(_translate("MainWindow", "8"))
        self.pushButton_17.setText(_translate("MainWindow", "9"))
        self.bolish.setText(_translate("MainWindow", "/"))
        self.pushButton_5.setText(_translate("MainWindow", "4"))
        self.pushButton_6.setText(_translate("MainWindow", "5"))
        self.pushButton_7.setText(_translate("MainWindow", "6"))
        self.kopaytrish.setText(_translate("MainWindow", "*"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_9.setText(_translate("MainWindow", "2"))
        self.pushButton_10.setText(_translate("MainWindow", "3"))
        self.olish.setText(_translate("MainWindow", "-"))
        self.qoshish.setText(_translate("MainWindow", "+"))
        self.teng.setText(_translate("MainWindow", "="))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.tozalash.setText(_translate("MainWindow", "C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
